/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EmploymentType = { 'internship' : null } |
  { 'contract' : null } |
  { 'partTime' : null } |
  { 'fullTime' : null };
export type ExperienceLevel = { 'mid' : null } |
  { 'junior' : null } |
  { 'lead' : null } |
  { 'senior' : null };
export type Id = bigint;
export interface JobApplication {
  'status' : { 'applied' : null } |
    { 'rejected' : null } |
    { 'interviewing' : null } |
    { 'offered' : null },
  'jobListingId' : Id,
  'timestamp' : bigint,
}
export interface JobListing {
  'id' : Id,
  'title' : string,
  'responsibilities' : Array<string>,
  'skillsRequired' : Array<string>,
  'description' : string,
  'employmentType' : EmploymentType,
  'company' : string,
  'timestamp' : bigint,
  'perks' : Array<string>,
  'salaryRange' : { 'max' : bigint, 'min' : bigint },
  'location' : string,
}
export interface PartialJobListing {
  'title' : string,
  'responsibilities' : Array<string>,
  'skillsRequired' : Array<string>,
  'description' : string,
  'employmentType' : EmploymentType,
  'company' : string,
  'perks' : Array<string>,
  'salaryRange' : { 'max' : bigint, 'min' : bigint },
  'location' : string,
}
export interface Profile {
  'bio' : string,
  'experienceLevel' : ExperienceLevel,
  'name' : string,
  'jobPreferences' : { 'onsite' : null } |
    { 'remote' : null } |
    { 'hybrid' : null },
  'email' : string,
  'resumeText' : string,
  'skills' : Array<string>,
  'location' : string,
  'desiredSalaryRange' : { 'max' : bigint, 'min' : bigint },
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateJobListingInput {
  'id' : Id,
  'title' : string,
  'responsibilities' : Array<string>,
  'skillsRequired' : Array<string>,
  'description' : string,
  'employmentType' : EmploymentType,
  'company' : string,
  'perks' : Array<string>,
  'salaryRange' : { 'max' : bigint, 'min' : bigint },
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJobListing' : ActorMethod<[PartialJobListing], Id>,
  'applyToJob' : ActorMethod<[Id], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteJobListing' : ActorMethod<[Id], undefined>,
  'getAllJobListings' : ActorMethod<[], Array<JobListing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallersSavedJobs' : ActorMethod<[Profile], Array<JobListing>>,
  'getCurrentJobApplicationsProfileInput' : ActorMethod<
    [Principal, Profile],
    Array<JobApplication>
  >,
  'getCurrentJobListings' : ActorMethod<
    [Principal, Profile],
    Array<JobListing>
  >,
  'getJobListing' : ActorMethod<[Id], JobListing>,
  'getLatestJobListings' : ActorMethod<[], Array<JobListing>>,
  'getSavedJobsProfileInput' : ActorMethod<
    [Principal, Profile],
    Array<JobListing>
  >,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'saveJob' : ActorMethod<[Id], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'swipeLeft' : ActorMethod<[Id], undefined>,
  'swipeRight' : ActorMethod<[Id], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unsaveJob' : ActorMethod<[Id], undefined>,
  'updateJobListing' : ActorMethod<[UpdateJobListingInput], Id>,
  'verifyToken' : ActorMethod<[string], Principal>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];