/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EmploymentType = IDL.Variant({
  'internship' : IDL.Null,
  'contract' : IDL.Null,
  'partTime' : IDL.Null,
  'fullTime' : IDL.Null,
});
export const PartialJobListing = IDL.Record({
  'title' : IDL.Text,
  'responsibilities' : IDL.Vec(IDL.Text),
  'skillsRequired' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'employmentType' : EmploymentType,
  'company' : IDL.Text,
  'perks' : IDL.Vec(IDL.Text),
  'salaryRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
  'location' : IDL.Text,
});
export const Id = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const JobListing = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'responsibilities' : IDL.Vec(IDL.Text),
  'skillsRequired' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'employmentType' : EmploymentType,
  'company' : IDL.Text,
  'timestamp' : IDL.Int,
  'perks' : IDL.Vec(IDL.Text),
  'salaryRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
  'location' : IDL.Text,
});
export const ExperienceLevel = IDL.Variant({
  'mid' : IDL.Null,
  'junior' : IDL.Null,
  'lead' : IDL.Null,
  'senior' : IDL.Null,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'experienceLevel' : ExperienceLevel,
  'name' : IDL.Text,
  'jobPreferences' : IDL.Variant({
    'onsite' : IDL.Null,
    'remote' : IDL.Null,
    'hybrid' : IDL.Null,
  }),
  'email' : IDL.Text,
  'resumeText' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
  'desiredSalaryRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
});
export const JobApplication = IDL.Record({
  'status' : IDL.Variant({
    'applied' : IDL.Null,
    'rejected' : IDL.Null,
    'interviewing' : IDL.Null,
    'offered' : IDL.Null,
  }),
  'jobListingId' : Id,
  'timestamp' : IDL.Int,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateJobListingInput = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'responsibilities' : IDL.Vec(IDL.Text),
  'skillsRequired' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'employmentType' : EmploymentType,
  'company' : IDL.Text,
  'perks' : IDL.Vec(IDL.Text),
  'salaryRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJobListing' : IDL.Func([PartialJobListing], [Id], []),
  'applyToJob' : IDL.Func([Id], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteJobListing' : IDL.Func([Id], [], []),
  'getAllJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallersSavedJobs' : IDL.Func([Profile], [IDL.Vec(JobListing)], ['query']),
  'getCurrentJobApplicationsProfileInput' : IDL.Func(
      [IDL.Principal, Profile],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getCurrentJobListings' : IDL.Func(
      [IDL.Principal, Profile],
      [IDL.Vec(JobListing)],
      ['query'],
    ),
  'getJobListing' : IDL.Func([Id], [JobListing], ['query']),
  'getLatestJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getSavedJobsProfileInput' : IDL.Func(
      [IDL.Principal, Profile],
      [IDL.Vec(JobListing)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'saveJob' : IDL.Func([Id], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'swipeLeft' : IDL.Func([Id], [], []),
  'swipeRight' : IDL.Func([Id], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unsaveJob' : IDL.Func([Id], [], []),
  'updateJobListing' : IDL.Func([UpdateJobListingInput], [Id], []),
  'verifyToken' : IDL.Func([IDL.Text], [IDL.Principal], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EmploymentType = IDL.Variant({
    'internship' : IDL.Null,
    'contract' : IDL.Null,
    'partTime' : IDL.Null,
    'fullTime' : IDL.Null,
  });
  const PartialJobListing = IDL.Record({
    'title' : IDL.Text,
    'responsibilities' : IDL.Vec(IDL.Text),
    'skillsRequired' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'employmentType' : EmploymentType,
    'company' : IDL.Text,
    'perks' : IDL.Vec(IDL.Text),
    'salaryRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
    'location' : IDL.Text,
  });
  const Id = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const JobListing = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'responsibilities' : IDL.Vec(IDL.Text),
    'skillsRequired' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'employmentType' : EmploymentType,
    'company' : IDL.Text,
    'timestamp' : IDL.Int,
    'perks' : IDL.Vec(IDL.Text),
    'salaryRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
    'location' : IDL.Text,
  });
  const ExperienceLevel = IDL.Variant({
    'mid' : IDL.Null,
    'junior' : IDL.Null,
    'lead' : IDL.Null,
    'senior' : IDL.Null,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'experienceLevel' : ExperienceLevel,
    'name' : IDL.Text,
    'jobPreferences' : IDL.Variant({
      'onsite' : IDL.Null,
      'remote' : IDL.Null,
      'hybrid' : IDL.Null,
    }),
    'email' : IDL.Text,
    'resumeText' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
    'desiredSalaryRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
  });
  const JobApplication = IDL.Record({
    'status' : IDL.Variant({
      'applied' : IDL.Null,
      'rejected' : IDL.Null,
      'interviewing' : IDL.Null,
      'offered' : IDL.Null,
    }),
    'jobListingId' : Id,
    'timestamp' : IDL.Int,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateJobListingInput = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'responsibilities' : IDL.Vec(IDL.Text),
    'skillsRequired' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'employmentType' : EmploymentType,
    'company' : IDL.Text,
    'perks' : IDL.Vec(IDL.Text),
    'salaryRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJobListing' : IDL.Func([PartialJobListing], [Id], []),
    'applyToJob' : IDL.Func([Id], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteJobListing' : IDL.Func([Id], [], []),
    'getAllJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallersSavedJobs' : IDL.Func(
        [Profile],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'getCurrentJobApplicationsProfileInput' : IDL.Func(
        [IDL.Principal, Profile],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getCurrentJobListings' : IDL.Func(
        [IDL.Principal, Profile],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'getJobListing' : IDL.Func([Id], [JobListing], ['query']),
    'getLatestJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getSavedJobsProfileInput' : IDL.Func(
        [IDL.Principal, Profile],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'saveJob' : IDL.Func([Id], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'swipeLeft' : IDL.Func([Id], [], []),
    'swipeRight' : IDL.Func([Id], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unsaveJob' : IDL.Func([Id], [], []),
    'updateJobListing' : IDL.Func([UpdateJobListingInput], [Id], []),
    'verifyToken' : IDL.Func([IDL.Text], [IDL.Principal], []),
  });
};

export const init = ({ IDL }) => { return []; };