/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface UpdateJobListingInput {
    id: Id;
    title: string;
    responsibilities: Array<string>;
    skillsRequired: Array<string>;
    description: string;
    employmentType: EmploymentType;
    company: string;
    perks: Array<string>;
    salaryRange: {
        max: bigint;
        min: bigint;
    };
    location: string;
}
export interface JobApplication {
    status: Variant_applied_rejected_interviewing_offered;
    jobListingId: Id;
    timestamp: bigint;
}
export interface JobListing {
    id: Id;
    title: string;
    responsibilities: Array<string>;
    skillsRequired: Array<string>;
    description: string;
    employmentType: EmploymentType;
    company: string;
    timestamp: bigint;
    perks: Array<string>;
    salaryRange: {
        max: bigint;
        min: bigint;
    };
    location: string;
}
export interface Profile {
    bio: string;
    experienceLevel: ExperienceLevel;
    name: string;
    jobPreferences: Variant_onsite_remote_hybrid;
    email: string;
    resumeText: string;
    skills: Array<string>;
    location: string;
    desiredSalaryRange: {
        max: bigint;
        min: bigint;
    };
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type Id = bigint;
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface PartialJobListing {
    title: string;
    responsibilities: Array<string>;
    skillsRequired: Array<string>;
    description: string;
    employmentType: EmploymentType;
    company: string;
    perks: Array<string>;
    salaryRange: {
        max: bigint;
        min: bigint;
    };
    location: string;
}
export enum EmploymentType {
    internship = "internship",
    contract = "contract",
    partTime = "partTime",
    fullTime = "fullTime"
}
export enum ExperienceLevel {
    mid = "mid",
    junior = "junior",
    lead = "lead",
    senior = "senior"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_applied_rejected_interviewing_offered {
    applied = "applied",
    rejected = "rejected",
    interviewing = "interviewing",
    offered = "offered"
}
export enum Variant_onsite_remote_hybrid {
    onsite = "onsite",
    remote = "remote",
    hybrid = "hybrid"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addJobListing(listing: PartialJobListing): Promise<Id>;
    applyToJob(jobListingId: Id): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteJobListing(jobId: Id): Promise<void>;
    getAllJobListings(): Promise<Array<JobListing>>;
    getCallerUserProfile(): Promise<Profile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCallersSavedJobs(profile: Profile): Promise<Array<JobListing>>;
    getCurrentJobApplicationsProfileInput(user: Principal, profile: Profile): Promise<Array<JobApplication>>;
    getCurrentJobListings(user: Principal, profile: Profile): Promise<Array<JobListing>>;
    getJobListing(id: Id): Promise<JobListing>;
    getLatestJobListings(): Promise<Array<JobListing>>;
    getSavedJobsProfileInput(user: Principal, profile: Profile): Promise<Array<JobListing>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<Profile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    saveCallerUserProfile(profile: Profile): Promise<void>;
    saveJob(jobListingId: Id): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    swipeLeft(jobListingId: Id): Promise<void>;
    swipeRight(jobListingId: Id): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unsaveJob(jobListingId: Id): Promise<void>;
    updateJobListing(input: UpdateJobListingInput): Promise<Id>;
    verifyToken(tokenId: string): Promise<Principal>;
}
import type { EmploymentType as _EmploymentType, ExperienceLevel as _ExperienceLevel, Id as _Id, JobApplication as _JobApplication, JobListing as _JobListing, PartialJobListing as _PartialJobListing, Profile as _Profile, StripeSessionStatus as _StripeSessionStatus, UpdateJobListingInput as _UpdateJobListingInput, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addJobListing(arg0: PartialJobListing): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.addJobListing(to_candid_PartialJobListing_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJobListing(to_candid_PartialJobListing_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async applyToJob(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyToJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyToJob(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteJobListing(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJobListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJobListing(arg0);
            return result;
        }
    }
    async getAllJobListings(): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobListings();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobListings();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallersSavedJobs(arg0: Profile): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallersSavedJobs(to_candid_Profile_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallersSavedJobs(to_candid_Profile_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentJobApplicationsProfileInput(arg0: Principal, arg1: Profile): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentJobApplicationsProfileInput(arg0, to_candid_Profile_n20(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentJobApplicationsProfileInput(arg0, to_candid_Profile_n20(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentJobListings(arg0: Principal, arg1: Profile): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentJobListings(arg0, to_candid_Profile_n20(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentJobListings(arg0, to_candid_Profile_n20(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobListing(arg0: Id): Promise<JobListing> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobListing(arg0);
                return from_candid_JobListing_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobListing(arg0);
            return from_candid_JobListing_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestJobListings(): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestJobListings();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestJobListings();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSavedJobsProfileInput(arg0: Principal, arg1: Profile): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedJobsProfileInput(arg0, to_candid_Profile_n20(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedJobsProfileInput(arg0, to_candid_Profile_n20(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_Profile_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_Profile_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveJob(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveJob(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async swipeLeft(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.swipeLeft(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.swipeLeft(arg0);
            return result;
        }
    }
    async swipeRight(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.swipeRight(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.swipeRight(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unsaveJob(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsaveJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsaveJob(arg0);
            return result;
        }
    }
    async updateJobListing(arg0: UpdateJobListingInput): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobListing(to_candid_UpdateJobListingInput_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobListing(to_candid_UpdateJobListingInput_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyToken(arg0: string): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyToken(arg0);
            return result;
        }
    }
}
function from_candid_EmploymentType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmploymentType): EmploymentType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ExperienceLevel_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExperienceLevel): ExperienceLevel {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_JobApplication_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobApplication): JobApplication {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_JobListing_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobListing): JobListing {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    experienceLevel: _ExperienceLevel;
    name: string;
    jobPreferences: {
        onsite: null;
    } | {
        remote: null;
    } | {
        hybrid: null;
    };
    email: string;
    resumeText: string;
    skills: Array<string>;
    location: string;
    desiredSalaryRange: {
        max: bigint;
        min: bigint;
    };
}): {
    bio: string;
    experienceLevel: ExperienceLevel;
    name: string;
    jobPreferences: Variant_onsite_remote_hybrid;
    email: string;
    resumeText: string;
    skills: Array<string>;
    location: string;
    desiredSalaryRange: {
        max: bigint;
        min: bigint;
    };
} {
    return {
        bio: value.bio,
        experienceLevel: from_candid_ExperienceLevel_n15(_uploadFile, _downloadFile, value.experienceLevel),
        name: value.name,
        jobPreferences: from_candid_variant_n17(_uploadFile, _downloadFile, value.jobPreferences),
        email: value.email,
        resumeText: value.resumeText,
        skills: value.skills,
        location: value.location,
        desiredSalaryRange: value.desiredSalaryRange
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        applied: null;
    } | {
        rejected: null;
    } | {
        interviewing: null;
    } | {
        offered: null;
    };
    jobListingId: _Id;
    timestamp: bigint;
}): {
    status: Variant_applied_rejected_interviewing_offered;
    jobListingId: Id;
    timestamp: bigint;
} {
    return {
        status: from_candid_variant_n28(_uploadFile, _downloadFile, value.status),
        jobListingId: value.jobListingId,
        timestamp: value.timestamp
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    title: string;
    responsibilities: Array<string>;
    skillsRequired: Array<string>;
    description: string;
    employmentType: _EmploymentType;
    company: string;
    timestamp: bigint;
    perks: Array<string>;
    salaryRange: {
        max: bigint;
        min: bigint;
    };
    location: string;
}): {
    id: Id;
    title: string;
    responsibilities: Array<string>;
    skillsRequired: Array<string>;
    description: string;
    employmentType: EmploymentType;
    company: string;
    timestamp: bigint;
    perks: Array<string>;
    salaryRange: {
        max: bigint;
        min: bigint;
    };
    location: string;
} {
    return {
        id: value.id,
        title: value.title,
        responsibilities: value.responsibilities,
        skillsRequired: value.skillsRequired,
        description: value.description,
        employmentType: from_candid_EmploymentType_n10(_uploadFile, _downloadFile, value.employmentType),
        company: value.company,
        timestamp: value.timestamp,
        perks: value.perks,
        salaryRange: value.salaryRange,
        location: value.location
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    internship: null;
} | {
    contract: null;
} | {
    partTime: null;
} | {
    fullTime: null;
}): EmploymentType {
    return "internship" in value ? EmploymentType.internship : "contract" in value ? EmploymentType.contract : "partTime" in value ? EmploymentType.partTime : "fullTime" in value ? EmploymentType.fullTime : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mid: null;
} | {
    junior: null;
} | {
    lead: null;
} | {
    senior: null;
}): ExperienceLevel {
    return "mid" in value ? ExperienceLevel.mid : "junior" in value ? ExperienceLevel.junior : "lead" in value ? ExperienceLevel.lead : "senior" in value ? ExperienceLevel.senior : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    onsite: null;
} | {
    remote: null;
} | {
    hybrid: null;
}): Variant_onsite_remote_hybrid {
    return "onsite" in value ? Variant_onsite_remote_hybrid.onsite : "remote" in value ? Variant_onsite_remote_hybrid.remote : "hybrid" in value ? Variant_onsite_remote_hybrid.hybrid : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    applied: null;
} | {
    rejected: null;
} | {
    interviewing: null;
} | {
    offered: null;
}): Variant_applied_rejected_interviewing_offered {
    return "applied" in value ? Variant_applied_rejected_interviewing_offered.applied : "rejected" in value ? Variant_applied_rejected_interviewing_offered.rejected : "interviewing" in value ? Variant_applied_rejected_interviewing_offered.interviewing : "offered" in value ? Variant_applied_rejected_interviewing_offered.offered : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n31(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobApplication>): Array<JobApplication> {
    return value.map((x)=>from_candid_JobApplication_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobListing>): Array<JobListing> {
    return value.map((x)=>from_candid_JobListing_n8(_uploadFile, _downloadFile, x));
}
function to_candid_EmploymentType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentType): _EmploymentType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ExperienceLevel_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceLevel): _ExperienceLevel {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_PartialJobListing_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartialJobListing): _PartialJobListing {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Profile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profile): _Profile {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateJobListingInput_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateJobListingInput): _UpdateJobListingInput {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    responsibilities: Array<string>;
    skillsRequired: Array<string>;
    description: string;
    employmentType: EmploymentType;
    company: string;
    perks: Array<string>;
    salaryRange: {
        max: bigint;
        min: bigint;
    };
    location: string;
}): {
    title: string;
    responsibilities: Array<string>;
    skillsRequired: Array<string>;
    description: string;
    employmentType: _EmploymentType;
    company: string;
    perks: Array<string>;
    salaryRange: {
        max: bigint;
        min: bigint;
    };
    location: string;
} {
    return {
        title: value.title,
        responsibilities: value.responsibilities,
        skillsRequired: value.skillsRequired,
        description: value.description,
        employmentType: to_candid_EmploymentType_n3(_uploadFile, _downloadFile, value.employmentType),
        company: value.company,
        perks: value.perks,
        salaryRange: value.salaryRange,
        location: value.location
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    experienceLevel: ExperienceLevel;
    name: string;
    jobPreferences: Variant_onsite_remote_hybrid;
    email: string;
    resumeText: string;
    skills: Array<string>;
    location: string;
    desiredSalaryRange: {
        max: bigint;
        min: bigint;
    };
}): {
    bio: string;
    experienceLevel: _ExperienceLevel;
    name: string;
    jobPreferences: {
        onsite: null;
    } | {
        remote: null;
    } | {
        hybrid: null;
    };
    email: string;
    resumeText: string;
    skills: Array<string>;
    location: string;
    desiredSalaryRange: {
        max: bigint;
        min: bigint;
    };
} {
    return {
        bio: value.bio,
        experienceLevel: to_candid_ExperienceLevel_n22(_uploadFile, _downloadFile, value.experienceLevel),
        name: value.name,
        jobPreferences: to_candid_variant_n24(_uploadFile, _downloadFile, value.jobPreferences),
        email: value.email,
        resumeText: value.resumeText,
        skills: value.skills,
        location: value.location,
        desiredSalaryRange: value.desiredSalaryRange
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Id;
    title: string;
    responsibilities: Array<string>;
    skillsRequired: Array<string>;
    description: string;
    employmentType: EmploymentType;
    company: string;
    perks: Array<string>;
    salaryRange: {
        max: bigint;
        min: bigint;
    };
    location: string;
}): {
    id: _Id;
    title: string;
    responsibilities: Array<string>;
    skillsRequired: Array<string>;
    description: string;
    employmentType: _EmploymentType;
    company: string;
    perks: Array<string>;
    salaryRange: {
        max: bigint;
        min: bigint;
    };
    location: string;
} {
    return {
        id: value.id,
        title: value.title,
        responsibilities: value.responsibilities,
        skillsRequired: value.skillsRequired,
        description: value.description,
        employmentType: to_candid_EmploymentType_n3(_uploadFile, _downloadFile, value.employmentType),
        company: value.company,
        perks: value.perks,
        salaryRange: value.salaryRange,
        location: value.location
    };
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceLevel): {
    mid: null;
} | {
    junior: null;
} | {
    lead: null;
} | {
    senior: null;
} {
    return value == ExperienceLevel.mid ? {
        mid: null
    } : value == ExperienceLevel.junior ? {
        junior: null
    } : value == ExperienceLevel.lead ? {
        lead: null
    } : value == ExperienceLevel.senior ? {
        senior: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_onsite_remote_hybrid): {
    onsite: null;
} | {
    remote: null;
} | {
    hybrid: null;
} {
    return value == Variant_onsite_remote_hybrid.onsite ? {
        onsite: null
    } : value == Variant_onsite_remote_hybrid.remote ? {
        remote: null
    } : value == Variant_onsite_remote_hybrid.hybrid ? {
        hybrid: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentType): {
    internship: null;
} | {
    contract: null;
} | {
    partTime: null;
} | {
    fullTime: null;
} {
    return value == EmploymentType.internship ? {
        internship: null
    } : value == EmploymentType.contract ? {
        contract: null
    } : value == EmploymentType.partTime ? {
        partTime: null
    } : value == EmploymentType.fullTime ? {
        fullTime: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
